//SELECTORS AND CONSTANTS INCLUDING AN ARRAY TO HOLD OUR STATE
//LISTEN FOR WHEN SOMEONE TYPES INTO THE INPUT
//KEEP TRACK OF THE ITEMS TO SEE IF THEY ARE COMPLETE
//RENDER OUT A LIST OF ALL ITEMS CREATED